<?php
/**
 *
 * @category    Jworks
 * @package     Jworks_UrlRewriteImport
 * @author Jitheesh V O <jitheeshvo@gmail.com>
 * @copyright Copyright (c) 2017 Jworks Digital ()
 */

// @codingStandardsIgnoreFile

?>
<div class="import-rewrites-container">
    <div class="import-rewrites">
        <form id="import-form" class="admin__fieldset" action="<?php /* @escapeNotVerified */ echo $block->getUrl('urlrewrite/import/importPost') ?>" method="post" enctype="multipart/form-data">
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="fieldset admin__field">
                <label for="import_rewrites_file" class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Import URL rewrites') ?></span></label>
                <div class="admin__field-control">
                    <input type="file" id="import_rewrites_file" name="import_rewrites_file" class="input-file required-entry"/>
                    <?php echo $block->getButtonHtml(__('Import URL rewrites'), '', 'import-submit') ?>
                </div>
            </div>




        </form>
        <script>
            require(['jquery', "mage/mage", "loadingPopup"], function(jQuery){
                jQuery('#import-form').mage('form').mage('validation');
                (function ($) {
                    $('.import-submit').click(function(){
                        if($(':input[name="import_rewrites_file"]').val()) {
                            $('body').loadingPopup({
                                timeout: false
                            });

                            $(this.form).submit();
                        }
                    });
                })(jQuery);
            });
        </script>
    </div>

    <div>
        <div>
            <h2>Example CSV</h2>
            <p>
                Attention: the CSV should be comma separated.
            </p>

            <img src="<?php echo $this->getViewFileUrl('Jworks_UrlRewriteImport::images/example-csv.png'); ?>" />
        </div>
    </div>

</div>
